<syntax>          ::= <rule> | <rule> <syntax>
<rule>            ::= <opt-whitespace> "<" <rule-name> ">" <opt-whitespace> "::=" <opt-whitespace> <expression> <line-end>
<whitespace>      ::= " "
<opt-whitespace>  ::= "" | <whitespace> <opt-whitespace>
<expression>      ::= <expression-list> | <expression-list> <opt-whitespace> "|" <opt-whitespace> <expression>
<line-end>        ::= <EOL> | <whitespace> <line-end>
<expression-list> ::= <term> | <term> <opt-whitespace> <expression-list>
<term>            ::= <literal> | "<" <rule-name> ">"
<literal>         ::= <doublequote> <opt-text> <doublequote>
<bnf-comment>     ::= "--" <opt-text> <line-end>
